- hosts: minerva_dataservices
  remote_user: vagrant
  roles:
     - common
     - zenoamaro.supervisord
     - postgres_postgis
     - geoserver
     - nginx
     - uwsgi
     - geonode
     - geonodegp
     - forecastio
