###
# Install forecastio data scraper
---
- name: Copy data tasks to main app
  synchronize: src=data_queues/ dest={{data_queues_root}}/

- name: Add data scraping task
  copy: src=forecastio_task.py dest={{geonodegp_tasks}}/
  notify: assemble tasks definition

- name: Add django settings
  copy: src=forecastio_settings.py dest={{geonodegp_settings}}/
  notify: assemble local_settings

- name: Create the forecastio coverage store
  uri:
    url: "{{geoserver_rest}}/workspaces/{{geonode_workspace}}/coveragestores.json"
    method: POST
    user: "{{geoserver_user}}"
    password: "{{geoserver_password}}"
    status_code:
      - 200
      - 201
    HEADER_Content-Type: application/json
    body: '{"coverageStore": {"enabled": true, "name": "forecastio", "type": "ImageMosaic", "workspace": "{{db_data_instance}}"}}'
    body_format: json
  ignore_errors: true

- name: Copy airtemp tif
  copy: src=forecast_io_airtemp_20150810T130000000Z.tif dest={{app_code_dir}}/{{app_name}}/forecastio/

- name: Copy indexer properties
  copy: src=indexer.properties dest={{app_code_dir}}/{{app_name}}/

- name: Copy timeregex properties
  copy: src=timeregex.properties dest={{app_code_dir}}/{{app_name}}/

- name: Generate datastore properties
  template: src=datastore.properties dest={{app_code_dir}}/{{app_name}}/

- name: Zip properties files
  command: zip forecastio.zip forecast_io_airtemp_20150810T130000000Z.tif indexer.properties timeregex.properties datastore.properties
  args:
    chdir: "{{app_code_dir}}/{{app_name}}"

- name: Use curl to add forecastio image mosaic
  command: curl --data-binary @forecastio.zip -XPUT -u {{geoserver_user}}:{{geoserver_password}} -H "Content-Type:application/zip" {{geoserver_rest}}/workspaces/{{db_data_instance}}/coveragestores/forecastio/file.imagemosaic 
  args:
    chdir: "{{app_code_dir}}/{{app_name}}"

- name: Generate coverage configuration
  template: src=coverage.json.j2 dest={{app_code_dir}}/{{app_name}}/coverage.json

- name: Create coverage
  command: curl --data @coverage.json -XPUT -u {{geoserver_user}}:{{geoserver_password}} -H Content-Type:application/json {{geoserver_rest}}/workspaces/{{db_data_instance}}/coveragestores/forecastio/coverages/forecastio.json
  args:
    chdir: "{{app_code_dir}}/{{app_name}}"
